---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: harshal
  become: false
  tasks:

    - name: Pull Docker Image
      docker_image:
        name: "iharshal/calculator"
        source: pull
      register: docker_pull_result

    - name: Stop existing container (if running)
      command: docker rm -f calculator
      ignore_errors: yes

    - name: Running container
      shell: docker run -it -d --name calculator iharshal/calculator



